k9s:
  refreshRate: 2
  maxConnRetry: 5
  enableMouse: false
  headless: false
  logoless: false
  crumbsless: false
  readOnly: false
  noIcons: false
  logger:
    tail: 100
    buffer: 5000
    sinceSeconds: 60
    fullScreenLogs: false
    textWrap: true
    showTime: false
  currentContext: gke_growi-cloud_asia-northeast1-a_growi-cloud-stg
  currentCluster: gke_growi-cloud_asia-northeast1-a_growi-cloud-stg
  clusters:
    gke_growi-cloud_asia-northeast1-a_growi-cloud-stg:
      namespace:
        active: growi-middlewares
        favorites:
        - growi-middlewares
        - default
      view:
        active: po
      featureGates:
        nodeShell: false
      shellPod:
        image: busybox:1.31
        command: []
        args: []
        namespace: default
        limits:
          cpu: 100m
          memory: 100Mi
      portForwardAddress: localhost
  thresholds:
    cpu:
      critical: 90
      warn: 70
    memory:
      critical: 90
      warn: 70
  screenDumpDir: /tmp/k9s-screens-ryu
